apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s-1
  labels:
    app: nodejs-k8s-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-k8s-1
  template:
    metadata:
      labels:
        app: nodejs-k8s-1 
    spec:
      containers:
      - name: nodejs-k8s-1
        image: gcr.io/nodejs-k8s-350419/github.com/mnm-hussain/ctse-assignment03-hussain
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

