apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-k8s-1
  template:
    metadata:
      labels:
        app: nodejs-k8s-1
    spec:
      containers:
        - name: nodejs-k8s-1
          image: huss99/ctse-assignment3-hussain:v1
          ports:
            - containerPort: 3000

