apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodejs-k8s-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-k8s-1
  template:
    metadata:
      labels:
        app: nodejs-k8s-1 
    spec:
      containers:
      - name: nodeserver
        image: gcr.io/kubernetes-project-350417/nodeapp:latest
        ports:
        - containerPort: 3000