apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodejs-k8s-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-k8s-1
  template:
    metadata:
      labels:
        app: nodejs-k8s-1 
    spec:
      containers:
      - name: nodeserver
        image: gcr.io/nodejs-k8s-350419/github.com/mnm-hussain/ctse-assignment03:v1
        ports:
        - containerPort: 3000
